/******************************** C2TPRIV.H ********************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!! (C) Copyright 1989 - 1995 Building Block Software  !!!!!!!!*/
/*!!!!!!!!                    All rights reserved                  !!!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
#ifndef     C2TPRIV
#define     C2TPRIV
#include    <c2defs.h>
#ifdef SPLINE
extern  REAL*   c2t_eval_hpt __(( HPT2 DUMMY0 , C2_TRANSFORM DUMMY1 ,
            HPT2 DUMMY2 )) ;
#endif /*SPLINE*/
#endif /* C2TPRIV*/

