/***************************** DX0HDR.H ************************************/
/*******************  Prototypes for dxf_hdr routines **********************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!!       (C) Copyright 1989 - 1995       Building Block Software   !!!!!!!*/
/*!!!!!!!!                    All rights reserved                   !!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
#ifndef     DX0HDR
#define     DX0HDR
#include <dxfdefs.h>
extern  int*        dx0_hdr_var_template __(( STRING DUMMY0 )) ;
extern  int         dx0_sizeof_template __(( int* DUMMY0 )) ;
extern  int *dx0_hdr_var_template_a __(( STRING )) ;
extern  int *dx0_hdr_var_template_c __(( STRING )) ;
extern  int *dx0_hdr_var_template_d __(( STRING )) ;
extern  int *dx0_hdr_var_template_p __(( STRING )) ;
extern  int *dx0_hdr_var_template_s __(( STRING )) ;
extern  int *dx0_hdr_var_template_u __(( STRING )) ;
#endif     /*DX0HDR*/


