/***************************** DXARCM.H **********************************/ 
#ifndef     DXARCM
#define     DXARCM 
#define     DXF_ARC_CTR(E)          (DX_ENTITY_ARC(E)->arc_ctr)
#define     DXF_ARC_RAD(E)          (DX_ENTITY_ARC(E)->arc_rad)
#define     DXF_ARC_ANG0(E)         (DX_ENTITY_ARC(E)->arc_ang0)
#define     DXF_ARC_ANG1(E)         (DX_ENTITY_ARC(E)->arc_ang1)
#endif      /* DXARCM */

