/****************************** DXLTPM.H ***********************************/ 
#ifndef     DXLTPM 
#define     DXLTPM 
#define     DXF_LTYPE_NAME(E)       (DX_TE_LTYPE(E)->ltype_name)
#define     DXF_LTYPE_FLAGS(E)      (DX_TE_LTYPE(E)->ltype_flags)
#define     DXF_LTYPE_TEXT(E)       (DX_TE_LTYPE(E)->ltype_text)
#define     DXF_LTYPE_ALGN(E)       (DX_TE_LTYPE(E)->ltype_algn)
#define     DXF_LTYPE_CNT(E)        (DX_TE_LTYPE(E)->ltype_count)
#define     DXF_LTYPE_TOT_LEN(E)    (DX_TE_LTYPE(E)->ltype_tot_len)
#define     DXF_LTYPE_LEN(E)        (DX_TE_LTYPE(E)->ltype_len)
#endif

