/****************************** DXSHPM.H ***********************************/ 
#ifndef     DXSHPM 
#define     DXSHPM 
#define     DXF_SHAPE_INSERT_PT(E)  (DX_ENTITY_SHAPE(E)->shape_insert_pt)
#define     DXF_SHAPE_SIZE(E)       (DX_ENTITY_SHAPE(E)->shape_size)
#define     DXF_SHAPE_NAME(E)       (DX_ENTITY_SHAPE(E)->shape_name)
#define     DXF_SHAPE_ROT_ANG(E)    (DX_ENTITY_SHAPE(E)->shape_rot_ang)
#define     DXF_SHAPE_X_SCALE(E)    (DX_ENTITY_SHAPE(E)->shape_x_scale)
#define     DXF_SHAPE_OBL_ANG(E)    (DX_ENTITY_SHAPE(E)->shape_obl_ang)
#endif

