/****************************** DXSTLM.H ***********************************/ 
#ifndef     DXSTLM 
#define     DXSTLM 
#define     DXF_STYLE_MIRRORED_X    2
#define     DXF_STYLE_MIRRORED_Y    4
#define     DXF_STYLE_NAME(E)       (DX_TE_STYLE(E)->style_name)
#define     DXF_STYLE_FLAGS(E)      (DX_TE_STYLE(E)->style_flags)
#define     DXF_STYLE_HEIGHT(E)     (DX_TE_STYLE(E)->style_height)
#define     DXF_STYLE_WIDTH(E)      (DX_TE_STYLE(E)->style_width)
#define     DXF_STYLE_OBL_ANG(E)    (DX_TE_STYLE(E)->style_obl_ang)
#define     DXF_STYLE_GFLAGS(E)     (DX_TE_STYLE(E)->style_gflags)
#define     DXF_STYLE_LAST_HT(E)    (DX_TE_STYLE(E)->style_last_ht)
#define     DXF_STYLE_FONT(E)       (DX_TE_STYLE(E)->style_font)
#define     DXF_STYLE_BIGFONT(E)    (DX_TE_STYLE(E)->style_bigfont)
#endif

