/****************************** DXTRAM.H ***********************************/ 
#ifndef     DXTRAM
#define     DXTRAM 
#define     DXF_TRACE_PT0(E)        (DX_ENTITY_TRACE(E)->trace_pt0) 
#define     DXF_TRACE_PT1(E)        (DX_ENTITY_TRACE(E)->trace_pt1) 
#define     DXF_TRACE_PT2(E)        (DX_ENTITY_TRACE(E)->trace_pt2) 
#define     DXF_TRACE_PT3(E)        (DX_ENTITY_TRACE(E)->trace_pt3) 
#endif


