/****************************** DXTWORD.H ***********************************/ 
#ifndef     DXTWORD 
#define     DXTWORD 
EXTERN  char    DXF_LTYPE_WORD[] ;
EXTERN  char    DXF_LAYER_WORD[] ;
EXTERN  char    DXF_STYLE_WORD[] ;
EXTERN  char    DXF_VIEW_WORD[]  ;
EXTERN  char    DXF_UCS_WORD[]   ;
EXTERN  char    DXF_VPORT_WORD[] ;
EXTERN  char    DXF_APPID_WORD[] ;
EXTERN  char    DXF_DIMSTYLE_WORD[] ;

#define DXF_LTYPE_TABLE_NAME        DXF_LTYPE_WORD 
#define DXF_LAYER_TABLE_NAME        DXF_LAYER_WORD 
#define DXF_STYLE_TABLE_NAME        DXF_STYLE_WORD 
#define DXF_VIEW_TABLE_NAME         DXF_VIEW_WORD 
#define DXF_UCS_TABLE_NAME          DXF_UCS_WORD   
#define DXF_VPORT_TABLE_NAME        DXF_VPORT_WORD 
#define DXF_APPID_TABLE_NAME        DXF_APPID_WORD 
#define DXF_DIMSTYLE_TABLE_NAME     DXF_DIMSTYLE_WORD 
#endif
