/*
$Workfile:   get_env.h  $

$Header:   P:/pvcs/sscope9/include/get_env.h_v   9.0   11 Mar 1996 11:22:14   softadmn  $

$Modtime:   18 Jan 1995 14:58:04  $

$Log:   P:/pvcs/sscope9/include/get_env.h_v  $
 * 
 *    Rev 9.0   11 Mar 1996 11:22:14   softadmn
 * Initial revision.
 * 
 *    Rev 8.0   18 Jan 1995 14:58:04   softadmn
 * Initial revision.
*/

int getEnvVar(char *tmp_env, char *env_variable, char *env_dflt);
