/******************************** T2ATTRD.H ********************************/
#ifndef T2ATTRD
#define T2ATTRD

#define     T2_ATTR_INIT          (ATTR)0
#define     T2_ATTR_PART          (ATTR)1
#define     T2_ATTR_ROUGH         (ATTR)2
#define     T2_ATTR_PROCESSED     (ATTR)4
#define     T2_ATTR_TOP           (ATTR)8
#define     T2_ATTR_EXTERIOR      (ATTR)8
#define     T2_ATTR_BOTTOM        (ATTR)16
#define     T2_ATTR_PROCSD_0      (ATTR)32
#define     T2_ATTR_PROCSD_1      (ATTR)64
#define     T2_ATTR_ARG1          (ATTR)32
#define     T2_ATTR_ARG2          (ATTR)64
#define     T2_ATTR_SUBTR         (ATTR)64
#define     T2_ATTR_MARGIN        (ATTR)64
#define     T2_ATTR_START_0       (ATTR)128
#define     T2_ATTR_START_1       (ATTR)256
#define     T2_ATTR_HORLINE       (ATTR)512
#define     T2_ATTR_FIRST         (ATTR)1024
#define     T2_ATTR_RETRACT       (ATTR)1024
#define     T2_ATTR_LAST          (ATTR)2048
#define     T2_ATTR_PLUNGE        (ATTR)2048
#define     T2_ATTR_RAPID         (ATTR)4096
#define     T2_ATTR_AUX           (ATTR)8192
#define     T2_ATTR_ADJUSTED      (ATTR)8192

#endif
