/******************************** T2DEFS.H *********************************/
/******************* definitions and macros for 2d topology ****************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!! (C) Copyright 1989 - 1995 Building Block Software  !!!!!!!!*/
/*!!!!!!!!                    All rights reserved                  !!!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
#ifndef T2DEFS
#define T2DEFS
#ifndef __BBS_MILL__ 
#define __BBS_MILL__ 3
#endif
#ifndef __BBS_TURN__ 
#define __BBS_TURN__ 3
#endif
#ifndef __BBS_WIRE__ 
#define __BBS_WIRE__ 3
#endif
#include <t2defs0.h>
#endif  /* T2DEFS */


